### PR TITLE
Add corrientes to tax list

### PR DESCRIPTION
**Pull request by Matuteale**
## Description
Add corrientes to tax list.

### Issue involved
Fixes #<issue>

### Checklist:
Before sending your contribution, please specify the following: 

- [x] This request modifies code snippets. 
- [ ] The contribution aligns with the information stated in the repository wiki.

- [ ] Contribution incorporates an article not included until now, which must be added to indexes as a new section. 
- [ ] Contribution includes new features. 
- [ ] New features were communicated in changelog.
- [ ] Requires translations.

### CODE REVIEW

**Review by lucmonzon — APPROVED** [review]

**Comment by lamaralmp** [comment]
Holá @Matuteale 

En `account-money/glossary` el cambio no debería estar también para PT y para EN?

**Comment by Matuteale** [comment]
@lamaralmp Gracias por el comentario, ya pedimos las traducciones para sumar el mismo contenido en los demás glosarios en y pt.

**Comment by Matuteale** [comment]
@lamaralmp ya quedó con las traducciones.

**Review by sanchezmauri — APPROVED** [review]
Aprobado.

**Review by lamaralmp — APPROVED** [review]

**Review by pamalv7 — APPROVED** [review]

**Pull request merged**
